/**
 * Created by mportugal on 5/15/14.
 */
public class Problem2 {

    /*
    Each new term in the Fibonacci sequence is generated by adding the previous two terms.
    By starting with 1 and 2, the first 10 terms will be:

    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

    By considering the terms in the Fibonacci sequence whose values do not exceed four million,
     find the sum of the even-valued terms.
    */

    public static void main(String args[]){

        System.out.println("Fibonacci sequence: " + doFibonacci(0, 1, 0));
    }

    public static int doFibonacci(int prev, int curr, int base){

       if (curr > 4000000)
           return base;

       if (curr % 2 == 0)
           base += curr;

       return doFibonacci(curr, prev + curr, base);


    }

}
